---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pso-collect
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pso-collect
rules:
- apiGroups: ["", "apps"]
  resources: ["secrets", "persistentvolumeclaims", "statefulsets", "pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pso-collect
subjects:
- kind: ServiceAccount
  name: pso-collect
  namespace: default
roleRef:
  kind: ClusterRole
  name: pso-collect
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pso-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pso-collect
  template:
    metadata:
      labels:
        app: pso-collect
    spec:
      serviceAccountName: pso-collect
      containers:
      - name: collect
        image: joshuarobinson/pso-analytics:0.1
        command: ["/bin/sh"]
        args: ["-c", "while true; do yes '' | sed 5q; python collect_storage_info.py; sleep 60; done"]
        imagePullPolicy: Always
      restartPolicy: Always
